/* The following code was generated by JFlex 1.7.0-SNAPSHOT tweaked for IntelliJ platform */

package com.rythmplugin;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import com.intellij.psi.TokenType;
import com.rythmplugin.psi.RythmTypes;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0-SNAPSHOT
 * from the specification file <tt>Rythm.flex</tt>
 */
class RythmLexer implements FlexLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   * Chosen bits are [7, 7, 7]
   * Total runtime size is 1928 bytes
   */
  public static int ZZ_CMAP(int ch) {
    return ZZ_CMAP_A[(ZZ_CMAP_Y[ZZ_CMAP_Z[ch>>14]|((ch>>7)&0x7f)]<<7)|(ch&0x7f)];
  }

  /* The ZZ_CMAP_Z table has 68 entries */
  static final char ZZ_CMAP_Z[] = zzUnpackCMap(
    "\1\0\103\200");

  /* The ZZ_CMAP_Y table has 256 entries */
  static final char ZZ_CMAP_Y[] = zzUnpackCMap(
    "\1\0\1\1\53\2\1\3\22\2\1\4\37\2\1\3\237\2");

  /* The ZZ_CMAP_A table has 640 entries */
  static final char ZZ_CMAP_A[] = zzUnpackCMap(
    "\11\0\1\2\1\1\1\13\2\1\22\0\1\2\1\16\1\36\5\0\1\25\1\26\2\0\1\40\1\0\1\24"+
    "\1\0\1\17\1\20\6\17\1\20\1\17\1\3\1\0\1\4\1\0\1\14\1\16\1\15\32\21\4\0\1\27"+
    "\1\0\1\33\1\22\1\6\1\23\1\30\1\23\1\35\1\22\1\10\1\22\1\23\1\34\3\23\1\11"+
    "\1\31\1\7\1\5\1\12\1\32\1\23\1\22\1\23\2\22\1\0\1\16\10\0\1\13\32\0\1\37\337"+
    "\0\1\37\177\0\13\37\35\0\2\13\5\0\1\37\57\0\1\37\40\0");

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\2\1\1\3\1\1\4\0\1\3"+
    "\10\0\2\3\2\0\1\4\25\0\1\5\2\0\1\4"+
    "\6\0\2\5\1\0\2\4\4\0\1\5\1\0\1\5"+
    "\2\4\5\0\1\6\2\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[78];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\41\0\102\0\143\0\204\0\245\0\306\0\347"+
    "\0\u0108\0\204\0\u0129\0\u014a\0\u016b\0\u018c\0\u01ad\0\u01ce"+
    "\0\u01ef\0\u0210\0\u0231\0\u0252\0\u0273\0\u0294\0\u02b5\0\u02d6"+
    "\0\41\0\u02f7\0\u0318\0\u0339\0\u035a\0\u037b\0\u039c\0\u03bd"+
    "\0\u03de\0\u03ff\0\u0420\0\u0441\0\u0462\0\u0483\0\u04a4\0\u04c5"+
    "\0\u04e6\0\u0507\0\u0528\0\u0549\0\u056a\0\u058b\0\u05ac\0\u05cd"+
    "\0\u05ee\0\u060f\0\u0630\0\u0651\0\u0672\0\u0693\0\u06b4\0\u06d5"+
    "\0\u06f6\0\u0717\0\u0738\0\u0759\0\u077a\0\u079b\0\u07bc\0\u07dd"+
    "\0\u07fe\0\41\0\u081f\0\u0840\0\u02b5\0\u0861\0\u0882\0\u08a3"+
    "\0\u08c4\0\u08e5\0\u0906\0\u0882\0\u0927\0\u0948";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[78];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\2\1\4\6\5\1\0\1\2\1\6"+
    "\3\2\3\5\1\7\3\2\6\5\3\2\42\0\2\3"+
    "\43\0\1\10\36\0\1\11\1\0\6\12\6\0\3\12"+
    "\4\0\6\12\3\0\1\13\1\0\3\13\6\14\1\0"+
    "\5\13\3\14\4\13\6\14\3\13\5\0\6\15\6\0"+
    "\3\15\4\0\1\16\4\15\1\17\11\0\1\20\33\0"+
    "\2\21\2\0\6\22\1\21\5\0\3\22\1\23\3\0"+
    "\6\22\1\24\1\21\6\0\1\25\1\0\4\25\3\0"+
    "\1\25\1\0\1\25\2\0\1\25\1\0\2\25\1\0"+
    "\1\25\2\0\1\25\1\0\1\25\10\0\1\25\1\26"+
    "\4\25\3\0\1\25\1\0\1\25\2\26\1\25\1\0"+
    "\2\25\1\0\1\25\2\26\1\25\1\26\1\25\10\0"+
    "\6\27\6\0\3\27\1\0\1\30\1\31\1\32\6\27"+
    "\10\0\6\27\6\0\3\27\1\0\1\30\1\31\1\32"+
    "\1\27\1\33\4\27\10\0\6\27\6\0\3\27\1\0"+
    "\1\30\1\31\1\32\1\34\5\27\12\0\1\35\32\0"+
    "\2\36\2\0\6\37\1\36\5\0\3\37\1\23\3\0"+
    "\6\37\1\40\1\36\6\0\6\22\6\0\3\22\1\41"+
    "\3\0\6\22\10\0\6\42\6\0\3\42\4\0\6\42"+
    "\10\0\6\43\6\0\3\43\4\0\6\43\10\0\6\25"+
    "\4\0\5\25\4\0\6\25\10\0\6\26\6\0\3\26"+
    "\4\0\6\26\10\0\6\27\6\0\3\27\1\0\1\44"+
    "\1\31\1\32\6\27\10\0\6\45\6\0\3\45\1\0"+
    "\1\30\1\31\1\0\6\45\24\0\1\46\3\0\1\44"+
    "\1\31\1\32\16\0\6\27\6\0\3\27\1\0\1\44"+
    "\1\31\1\32\2\27\1\47\3\27\10\0\5\27\1\50"+
    "\6\0\3\27\1\0\1\44\1\31\1\32\6\27\13\0"+
    "\1\51\31\0\2\36\2\0\6\37\1\36\5\0\3\37"+
    "\1\23\3\0\6\37\1\52\1\36\6\0\6\37\6\0"+
    "\3\37\1\23\3\0\6\37\10\0\6\53\6\0\3\53"+
    "\4\0\6\53\10\0\6\54\6\0\3\54\4\0\6\54"+
    "\10\0\6\42\6\0\3\42\1\0\1\55\2\0\6\42"+
    "\10\0\6\43\6\0\3\43\1\56\3\0\6\43\1\57"+
    "\1\0\1\60\25\0\1\44\1\31\17\0\6\45\6\0"+
    "\3\45\2\0\1\31\1\0\6\45\24\0\1\46\3\0"+
    "\1\44\1\31\17\0\6\27\6\0\3\27\1\0\1\44"+
    "\1\31\1\32\3\27\1\61\2\27\10\0\6\62\6\0"+
    "\3\62\1\0\1\44\1\31\1\32\6\62\14\0\1\63"+
    "\34\0\6\64\6\0\3\64\4\0\6\64\10\0\6\53"+
    "\6\0\3\53\1\65\3\0\6\53\10\0\6\54\6\0"+
    "\3\54\1\0\1\66\2\0\6\54\31\0\1\67\17\0"+
    "\6\70\6\0\3\70\1\56\3\0\6\70\1\71\7\0"+
    "\6\70\6\0\3\70\1\56\1\0\1\71\1\0\6\70"+
    "\1\57\1\0\1\72\5\0\6\70\6\0\3\70\1\56"+
    "\3\0\6\70\1\71\1\0\1\60\5\0\6\27\6\0"+
    "\3\27\1\0\1\44\1\31\1\32\4\27\1\73\1\27"+
    "\10\0\6\62\6\0\3\62\1\0\1\74\1\75\1\32"+
    "\6\62\15\0\1\76\33\0\6\64\6\0\3\64\1\77"+
    "\3\0\6\64\10\0\6\100\6\0\3\100\4\0\6\100"+
    "\10\0\6\101\6\0\3\101\2\0\1\67\1\0\6\101"+
    "\43\0\1\102\5\0\6\70\6\0\3\70\1\103\3\0"+
    "\6\70\1\71\30\0\1\71\11\0\1\104\5\0\6\70"+
    "\6\0\3\70\1\56\3\0\6\70\1\71\1\0\1\72"+
    "\5\0\1\105\5\27\6\0\3\27\1\0\1\44\1\31"+
    "\1\32\6\27\10\0\6\106\6\0\3\106\1\0\1\74"+
    "\1\75\1\0\6\106\31\0\1\75\12\0\1\76\1\0"+
    "\11\76\1\0\1\107\24\76\5\0\6\110\6\0\3\110"+
    "\4\0\6\110\10\0\6\100\6\0\3\100\1\111\3\0"+
    "\6\100\1\67\7\0\6\101\6\0\3\101\1\112\3\0"+
    "\6\101\10\0\6\113\6\0\3\113\1\103\3\0\6\113"+
    "\1\71\42\0\1\104\5\0\6\106\6\0\3\106\2\0"+
    "\1\75\1\0\6\106\3\0\1\107\1\0\11\107\1\0"+
    "\1\114\24\107\5\0\6\110\6\0\3\110\4\0\6\110"+
    "\1\67\7\0\6\113\6\0\3\113\4\0\6\113\10\0"+
    "\6\115\6\0\3\115\4\0\6\115\10\0\6\113\6\0"+
    "\3\113\4\0\6\113\1\71\7\0\6\115\6\0\3\115"+
    "\1\0\1\116\2\0\6\115\31\0\1\55\12\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2409];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\5\1\4\0\1\1\10\0\2\1\2\0"+
    "\1\11\25\0\1\1\2\0\1\1\6\0\2\1\1\0"+
    "\2\1\4\0\1\11\1\0\3\1\5\0\1\1\2\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[78];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  RythmLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    int size = 0;
    for (int i = 0, length = packed.length(); i < length; i += 2) {
      size += packed.charAt(i);
    }
    char[] map = new char[size];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < packed.length()) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart() {
    return zzStartRead;
  }

  public final int getTokenEnd() {
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end, int initialState) {
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL/*, zzEndReadL*/);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL/*, zzEndReadL*/);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + ZZ_CMAP(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        zzDoEOF();
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return TokenType.BAD_CHARACTER;
            }
          case 7: break;
          case 2: 
            { yybegin(YYINITIAL); return TokenType.WHITE_SPACE;
            }
          case 8: break;
          case 3: 
            { yybegin(YYINITIAL); return RythmTypes.RYTHM_KEY;
            }
          case 9: break;
          case 4: 
            { yybegin(YYINITIAL); return RythmTypes.RYTHM_METHOD;
            }
          case 10: break;
          case 5: 
            { yybegin(YYINITIAL); return RythmTypes.RYTHM_BLOCK;
            }
          case 11: break;
          case 6: 
            { yybegin(YYINITIAL); return RythmTypes.SCRIPT;
            }
          case 12: break;
          default:
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
