{
  parserClass="com.rythmplugin.parser.RythmParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Rythm"
  psiImplClassSuffix="Impl"
  psiPackage="com.rythmplugin.psi"
  psiImplPackage="com.rythmplugin.psi.impl"

  elementTypeHolderClass="com.rythmplugin.psi.RythmTypes"
  elementTypeClass="com.rythmplugin.psi.RythmElementType"
  tokenTypeClass="com.rythmplugin.psi.RythmTokenType"
}

rythmFile ::= item_*

private item_ ::= (property|COMMENT|CRLF|rythm)

property ::= (/*KEY?*/ SEPARATOR VALUE?) | /*KEY*/

rythm ::= (rythmat|rythmif|rythmfor|rythmwhile)

rythmat ::= AT

rythmif ::= AT_IF

rythmwhile ::= AT_WHILE

rythmfor ::= AT_FOR